'use client'

import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isNav = pathname.startsWith('/login') || pathname.startsWith('/register')
  return (
    <html lang="en">
      <body className={inter.className}>
        {!isNav && <Navbar />}
        {children}
      </body>
    </html>
  )
}
