'use client'

import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { usePathname } from 'next/navigation'
import { SessionProvider } from "next-auth/react"
import Footer from '@/components/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({children}) {
  const pathname = usePathname()
  const isNav = pathname.startsWith('/login') || pathname.startsWith('/register')
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {!isNav && <Navbar />}
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  )
}
